services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: paulflood
      POSTGRES_PASSWORD: paulflood
      POSTGRES_DB: paulflood
    volumes:
      - paulflood_pg:/var/lib/postgresql/data

volumes:
  paulflood_pg:
